### PR TITLE
Employee page

### PR DESCRIPTION
**Pull request by Jdure**
Added testing to edit employee

### CODE REVIEW

**Comment by e-wu** [comment]
@Jdure 
- [x] Fix conflict please
- [ ] the location.js file seems to mangle the locality of the tests. Is there a reason why we need it as the test code is now more than just 1 file? everything related to homepage should be in homepage unless it is "common" code.
- [x] add  mochawesome-report to .gitignore and delete the ones already committed.

Later
- Please add eslint and prettier to project so we can format code

**Comment by Jdure** [comment]
> @Jdure
> 
> * [x]  Fix conflict please
> * [ ]  the location.js file seems to mangle the locality of the tests. Is there a reason why we need it as the test code is now more than just 1 file? everything related to homepage should be in homepage unless it is "common" code.
> * [x]  add  mochawesome-report to .gitignore and delete the ones already committed.
> 
> Later
> 
> * Please add eslint and prettier to project so we can format code

@e-wu I fixed the conflict, added mochawesome to .gitignore and added eslint to the project. Please, have a look at the PR

**Comment by e-wu** [comment]
Still wondering what location.js serves? Do we need it?
Asking because as we add more pages, adding this to location.js bleeds the test code across multiple files.

**Comment by Jdure** [comment]
> Still wondering what location.js serves? Do we need it?
> Asking because as we add more pages, adding this to location.js bleeds the test code across multiple files.

I was using it to easily reference the different css selectors but I see your point in regards to the multiple files.

**Comment by Jdure** [comment]
> > Still wondering what location.js serves? Do we need it?
> > Asking because as we add more pages, adding this to location.js bleeds the test code across multiple files.
> 
> I was using it to easily reference the different css selectors but I see your point in regards to the multiple files.

**Pull request merged**
